spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  flyway:
    enabled: true
    locations: classpath:db/migration
  mail:
    host: ${MAIL_HOST}
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
springdoc:
  swagger-ui:
    path: ${SWAGGER_UI_PATH}
    operationsSorter: ${SWAGGER_UI_OPERATIONS_SORTER}
auth:
  jwt:
    secret: ${JWT_SECRET}
com:
  fzerey:
    user:
      initial:
        attributes: ${USER_INITIAL_ATTRIBUTES}
